name: Clone Releases
on:
  # kick off the job on demand
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        uses: andrewthetechie/gha-clone-releases@v1
        with:
          token: ${{ secrets.PRIVATE_RELEASES_ACCESS_TOKEN }}
          src_repo: ADMSCentre/mortar
          copy_assets: true
          skip_draft: true
          skip_prerelease: true
